import { useState, type ReactNode } from 'react';
import { Link } from '@tanstack/react-router';
import { X, UserRound, Package, Bell, Settings, Heart, Headphones } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageShell, MobileTabBar } from './page-shell';
import { ShopTopBar, ShopTitle } from './shop-product-card';
import { useDemoProfile } from '@/lib/demo-profile';
const sections=[['Dashboard','',UserRound],['Orders','orders',Package],['Notifications','notifications',Bell],['Settings','settings',Settings]] as const;
export function AccountNav({active=''}:{active?:string}){const {profile}=useDemoProfile();return <aside className="acc-nav"><div className="acc-nav-profile"><span className="acc-avatar">{profile.name?profile.name.split(' ').map(s=>s[0]).slice(0,2).join(''):<UserRound/>}</span><strong>{profile.name||'Guest parent'}</strong></div><nav aria-label="Account navigation">{sections.map(([label,section,Icon])=>section?<Link to="/account/$section" params={{section}} key={label} className={active===section?'acc-selected':''}><Icon/>{label}</Link>:<Link to="/account" key={label} className={!active?'acc-selected':''}><Icon/>{label}</Link>)}<Link to="/wishlist"><Heart/>Wishlist</Link><Link to="/support"><Headphones/>Support</Link></nav></aside>}
export function AccountLayout({title,active='',children}:{title:string;active?:string;children:ReactNode}){const [banner,setBanner]=useState(true);return <PageShell className="spc-page acc-page"><ShopTopBar title={title} subtitle="Your little family's corner"/><div className="spc-wrap"><ShopTitle title={title} section="Account"/>{banner&&<div className="acc-demo">Demo account — details are saved only on this device.<Button type="button" variant="ghost" size="icon" aria-label="Dismiss demo notice" onClick={()=>setBanner(false)}><X/></Button></div>}<div className="acc-layout"><AccountNav active={active}/><div className="acc-content">{children}</div></div></div><MobileTabBar active="account"/></PageShell>}
export function PasswordStrength({value}:{value:string}){const score=Number(value.length>=6)+Number(value.length>=10)+Number(/[A-Z]/.test(value)&&/[a-z]/.test(value))+Number(/\d/.test(value)&&/[^\w]/.test(value));return <div className={`acc-strength acc-strength-${score}`}><div>{[1,2,3,4].map(n=><span className={n<=score?'acc-filled':''} key={n}/>)}</div><small>{value?['Weak','Weak','OK','Good','Strong'][score]:'Password strength'}</small></div>}
