import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { Check, Copy, Package, Truck, Home, Download } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { AccountLayout } from './account-nav';
import { useCart, totals, type Order } from '@/lib/cart-store';
import { getProduct, tk } from '@/lib/products';
export function OrderCard({order}:{order:Order}){const {add,address}=useCart();const bill=totals(order.lines);return <section className="acc-card acc-order"><div className="acc-order-head"><div><h2>{order.number}</h2><p>{order.placed}</p></div><Button type="button" variant="ghost" size="icon" aria-label="Copy order number" onClick={()=>{void navigator.clipboard.writeText(order.number).then(()=>toast.success('Order number copied'))}}><Copy/></Button><span className="acc-status">Placed</span></div><div className="acc-tracker">{[[Check,'Placed'],[Package,'Packed'],[Truck,'On the way'],[Home,'Delivered']].map(([Icon,label],i)=>{const I=Icon as typeof Check;return <div key={String(label)} className={i===0?'acc-done':''}><I/><span>{String(label)}</span></div>})}</div>{order.lines.map(l=>{const p=getProduct(l.slug);return p?<div className="acc-order-item" key={`${l.slug}-${l.size}`}><img src={p.image} alt=""/><Link to="/product/$slug" params={{slug:p.slug}}><strong>{p.name}</strong><small>{l.size} · {l.qty} × ৳{tk(p.price)}</small></Link><b>৳{tk(p.price*l.qty)}</b></div>:null})}<p>Payment: {order.payment}</p><p>Delivery address: {address}</p><dl className="acc-totals">{[['Subtotal',bill.subtotal],['Discount',-bill.discount],['Delivery',bill.delivery],['Total',bill.total]].map(([label,n])=><div key={label}><dt>{label}</dt><dd>৳{tk(Number(n))}</dd></div>)}</dl><div className="acc-actions"><Button type="button" variant="ghost" className="spc-primary" onClick={()=>{order.lines.forEach(l=>{const p=getProduct(l.slug);if(p)add(p,l.size,l.qty)});toast.success('Order items added to cart')}}>Reorder all</Button><Button type="button" variant="ghost" asChild className="spc-chip"><Link to="/support">Need help?</Link></Button><span title="Available when accounts launch"><Button type="button" variant="ghost" disabled><Download/>Download invoice</Button></span></div></section>}
export function AccountOrders(){const {lastOrder}=useCart();const [tab,setTab]=useState('All');const show=lastOrder&&(tab==='All'||tab==='Active');return <AccountLayout title="My orders" active="orders"><div className="spc-chip-row">{['All','Active','Delivered','Cancelled'].map(t=><Button type="button" variant="ghost" key={t} className={`spc-chip ${tab===t?'spc-on':''}`} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t} ({lastOrder&&(t==='All'||t==='Active')?1:0})</Button>)}</div>{show?<OrderCard order={lastOrder}/>:<section className="acc-card acc-empty"><Package/><h2>No orders yet</h2><p>Your orders will appear here after checkout.</p><Button type="button" asChild variant="ghost" className="spc-primary"><Link to="/">Start shopping</Link></Button></section>}</AccountLayout>}
