import { useState, type ReactNode } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, ShieldCheck, Heart } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageShell, MobileTabBar } from './page-shell';
import { ShopTopBar, ShopTitle, ShopSection } from './shop-product-card';
import { brands, type Brand } from '@/lib/brands';
import { products } from '@/lib/products';
import { LogoHeart } from '@/components/home-design/art';
export function BrandLogo({brand}:{brand:Brand}){return <span className={`brd-logo ${brand.tint}`}>{brand.name==='Baby Choice'?<LogoHeart/>:brand.logo?<img src={brand.logo} alt={`${brand.name} logo`}/>:<span>{brand.name.slice(0,1)}</span>}</span>}
export function BrandLink({brand,children,className}:{brand:Brand;children:ReactNode;className?:string}){return brand.slug==='johnsons'?<Link to="/brands/johnsons" className={className}>{children}</Link>:<Link to="/brands/$brand" params={{brand:brand.slug}} className={className}>{children}</Link>}
export function BrandTile({brand:b}:{brand:Brand}){return <BrandLink brand={b} className={`brd-tile ${b.accent}`}><BrandLogo brand={b}/><div><h3>{b.displayName}</h3>{b.name==='Baby Choice'&&<small>Our own range</small>}<p>{b.count} {b.count===1?'product':'products'} · ★{b.avgRating}</p><div className="brd-mini-chips">{b.categories.slice(0,2).map(c=><span key={c}>{c}</span>)}{b.categories.length>2&&<span>+{b.categories.length-2}</span>}</div>{b.maxOff>0&&<span className="brd-deal">Up to {b.maxOff}% off</span>}<span className="brd-shop">Shop {b.displayName} <ArrowRight/></span></div></BrandLink>}
const filters:Record<string,string[]>={'Bath & skin':['Bath & Skin'],'Feeding':['Feeding'],'Diapers':['Diapers'],'Toys':['Toys'],'Clothing':['Clothing']};
export function BrandsPage(){const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');const items=brands.filter(b=>b.displayName.toLowerCase().includes(query.toLowerCase())&&(filter==='All'||filter==='On sale'&&b.maxOff>0||filters[filter]?.some(c=>b.categories.includes(c))));const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');const featured=[...items].sort((a,b)=>b.totalReviews-a.totalReviews).slice(0,4);return <PageShell className="spc-page brd-page"><ShopTopBar title="Brands" subtitle={`${brands.length} brands · ${products.length} products`}/><div className="spc-wrap"><ShopTitle title="Brands" section="Brands" count={`${brands.length} brands · ${products.length} products`}/><section className="brd-hero"><div><span className="spc-eyebrow">LITTLE FAVOURITES</span><h2>Brands parents trust</h2><p>{products.length} products from {brands.length} brands</p><label className="brd-search">Find a brand<input type="search" placeholder="Find a brand" value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/></label></div><div className="brd-hero-logos">{featured.map(b=><BrandLogo key={b.slug} brand={b}/>)}</div></section><div className="spc-chip-row">{['All','On sale',...Object.keys(filters)].map(f=><Button type="button" variant="ghost" key={f} className={`spc-chip ${f===filter?'spc-on':''}`} aria-pressed={f===filter} onClick={()=>setFilter(f)}>{f}</Button>)}</div><div className="brd-layout"><aside className="brd-az" aria-label="Alphabet navigation">{letters.map(l=>{const enabled=items.some(b=>b.name.startsWith(l));return <Button type="button" variant="ghost" key={l} disabled={!enabled} aria-disabled={!enabled} onClick={()=>document.getElementById(`brd-letter-${l}`)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}>{l}</Button>})}</aside><div className="brd-content"><ShopSection eyebrow="LOVED BY PARENTS" title="Featured brands"/><div className="brd-featured">{featured.map(b=><BrandTile key={b.slug} brand={b}/>)}</div><ShopSection eyebrow="FIND YOUR FAVOURITES" title="All brands"/><p className="brd-count" aria-live="polite">{items.length} brands</p>{letters.map(l=>{const group=items.filter(b=>b.name.startsWith(l));return group.length>0?<section id={`brd-letter-${l}`} className="brd-group" key={l}><h2>{l}</h2><div className="brd-grid">{group.map(b=><BrandTile key={b.slug} brand={b}/>)}</div></section>:null})}{!items.length&&<section className="brd-empty"><Heart/><h2>No brands found</h2><Button type="button" variant="ghost" className="spc-chip" onClick={()=>{setQuery('');setFilter('All')}}>Clear filters</Button></section>}</div></div><section className="brd-promise"><ShieldCheck/><h2>Original products from authorised sources</h2></section></div><MobileTabBar active="categories"/></PageShell>}
