import { useState, type ReactNode } from 'react';
import { Link, useNavigate } from '@tanstack/react-router';
import { Droplets, ShieldCheck, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageShell, MobileTabBar } from './page-shell';
import { ShopProductCard, ShopSection, ShopTopBar, ShopTitle, ShopViewToggle } from './shop-product-card';
import { BrandLogo } from './brands-page';
import { brandSorts, sortBrandProducts } from './brand-page';
import { brands } from '@/lib/brands';
import { johnsons, off, tk } from '@/lib/products';
import { useCart } from '@/lib/cart-store';
const brand=brands.find(b=>b.slug==='johnsons');const types=[...new Set(johnsons.map(p=>p.type).filter((t):t is string=>!!t))];const popular=sortBrandProducts(johnsons,'Popular');
function JohnsonsHeader({active}:{active:string}){return <><section className="jnj-banner">{brand&&<BrandLogo brand={brand}/>}<div><h2>Johnson's</h2><p>{johnsons.length} products · ★{brand?.avgRating} · {brand?.totalReviews} reviews</p></div></section><nav className="jnj-tabs" aria-label="Johnson's pages">{[['Overview','/brands/johnsons'],['All products','/brands/johnsons/products'],['Our story','/brands/johnsons/story']].map(([label,to])=><Link key={to} to={to as '/brands/johnsons'|'/brands/johnsons/products'|'/brands/johnsons/story'} aria-current={active===label?'page':undefined} className={active===label?'jnj-active':''}>{label}</Link>)}</nav></>}
function JohnsonsLayout({active,children}:{active:string;children:ReactNode}){return <PageShell className="spc-page brd-page jnj-page"><ShopTopBar title="Johnson's" subtitle={`${johnsons.length} products`}/><div className="spc-wrap"><ShopTitle title={active==='Overview'?"Johnson's":`Johnson's · ${active}`} section={`Brands › Johnson's › ${active}`}/><JohnsonsHeader active={active}/>{children}</div><MobileTabBar active="categories"/></PageShell>}
export function JohnsonsOverview(){const {add}=useCart();const routine=['Body Wash','Lotion','Powder'].flatMap(t=>{const p=johnsons.find(p=>p.type===t);return p?[p]:[]});return <JohnsonsLayout active="Overview"><ShopSection eyebrow="EVERYDAY BABY CARE" title="Shop by product type"/><div className="jnj-types">{types.map((t,i)=>{const items=johnsons.filter(p=>p.type===t);return <Link to="/brands/johnsons/products" search={{type:t,sort:'Popular'}} key={t} className={`jnj-type spc-tint-${i%7}`}><img src={items[0]?.image} alt=""/><strong>{t}</strong><small>{items.length} {items.length===1?'product':'products'}</small><ArrowRight/></Link>})}</div><ShopSection eyebrow="RANKED BY REVIEWS" title="Most loved Johnson's"/><div className="spc-grid">{popular.slice(0,4).map((p,i)=><ShopProductCard key={p.slug} product={p} tint={i}/>)}</div><ShopSection eyebrow="REAL SAVINGS" title="On offer"/><div className="spc-grid">{johnsons.filter(p=>off(p)>0).map((p,i)=><ShopProductCard key={p.slug} product={p} tint={i}/>)}</div><section className="jnj-routine"><div><Droplets/><span className="spc-eyebrow">A LITTLE CARE ROUTINE</span><h2>Build a bath-time routine</h2></div><div className="jnj-routine-steps">{routine.map((p,i)=><div key={p.slug}><span>{i+1} · {['Wash','Moisturise','Dry and protect'][i]}</span><img src={p.image} alt=""/><Link to="/product/$slug" params={{slug:p.slug}}>{p.name}</Link><strong>৳{tk(p.price)}</strong></div>)}</div><div className="jnj-routine-foot"><strong>Total ৳{tk(routine.reduce((n,p)=>n+p.price,0))}</strong><Button type="button" variant="ghost" className="spc-primary" onClick={e=>{routine.forEach(p=>add(p,undefined,1,e.currentTarget))}}>Add all {routine.length} to cart</Button></div></section></JohnsonsLayout>}
export function JohnsonsProducts({type='All',sort='Popular'}:{type?:string;sort?:string}){const navigate=useNavigate();const [list,setList]=useState(false);const items=sortBrandProducts(johnsons.filter(p=>type==='All'||p.type===type),sort);return <JohnsonsLayout active="All products"><nav className="spc-chip-row" aria-label="Product types">{['All',...types].map(t=><Button type="button" variant="ghost" className={`spc-chip ${t===type?'spc-on':''}`} aria-pressed={t===type} key={t} onClick={()=>{void navigate({to:'/brands/johnsons/products',search:{type:t,sort}})}}>{t} ({t==='All'?johnsons.length:johnsons.filter(p=>p.type===t).length})</Button>)}</nav><div className="spc-toolbar"><label className="spc-sort">Sort<select aria-label="Sort Johnson's products" value={sort} onChange={e=>{void navigate({to:'/brands/johnsons/products',search:{type,sort:e.target.value}})}}>{brandSorts.map(s=><option key={s}>{s}</option>)}</select></label><ShopViewToggle list={list} setList={setList}/><span aria-live="polite">{items.length} products</span></div><div className={`spc-grid ${list||items.length<=3?'spc-list-grid':''}`}>{items.map((p,i)=><ShopProductCard product={p} key={p.slug} tint={i} variant={list||items.length<=3?'list':'grid'}/>)}</div>{!items.length&&<section className="brd-empty"><h2>No products for this type</h2></section>}</JohnsonsLayout>}
export function JohnsonsStory(){return <JohnsonsLayout active="Our story"><section className="jnj-editorial"><div><span className="spc-eyebrow">EVERYDAY CARE</span><h2>Gentle by design</h2><p>Baby care can be a simple part of a daily routine. Explore wash, lotion and other care essentials in our catalogue.</p><span className="acc-placeholder">[Brand history fact]</span></div><div className="jnj-image"><img src={johnsons[0]?.image} alt="Johnson's baby care product"/></div></section><section className="jnj-editorial jnj-reverse"><div><h2>Their range at Baby Choice</h2><div className="brd-stat-chips">{types.map(t=><span key={t}>{t}: {johnsons.filter(p=>p.type===t).length}</span>)}</div><span className="acc-placeholder">[Brand history fact]</span></div><div className="jnj-image spc-tint-3"><img src={johnsons.find(p=>p.type==='Lotion')?.image} alt="Johnson's lotion"/></div></section><section className="brd-promise"><ShieldCheck/><div><h2>How we source</h2><p>Original products from authorised sources</p></div></section><ShopSection eyebrow="LITTLE FAVOURITES" title="Featured products"/><div className="spc-grid">{popular.slice(0,4).map((p,i)=><ShopProductCard key={p.slug} product={p} tint={i}/>)}</div></JohnsonsLayout>}
