import { useEffect, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { Zap, Truck, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageShell, MobileTabBar } from './page-shell';
import { ShopProductCard, ShopTopBar, ShopTitle, ShopSection, ShopHeroPhotos } from './shop-product-card';
import { products, off, tk } from '@/lib/products';
import { catalogCategories } from '@/lib/catalog-demo';
import { getCategoryListing } from '@/lib/home-categories';
import { slugify } from '@/lib/live-head';
const deals=products.filter(p=>off(p)>0).sort((a,b)=>off(b)-off(a));const flash=deals.slice(0,8);const maxOff=Math.max(0,...deals.map(off));
const groups=[{name:'All deals',items:deals},{name:'Flash deals',items:flash},{name:'Under ৳500',items:deals.filter(p=>p.price<500)},{name:'Bundles & gift sets',items:deals.filter(p=>/gift|set|pack/i.test(`${p.name} ${p.type??''}`))},{name:'Big savings',items:deals.filter(p=>p.old-p.price>=400).sort((a,b)=>(b.old-b.price)-(a.old-a.price))},{name:'New arrivals on sale',items:deals.filter(p=>/new/i.test(p.badge??''))}].filter(g=>g.items.length);
const categoryDeals=catalogCategories.flatMap(c=>{const slug=slugify(c.name);const items=getCategoryListing(slug).items.filter(p=>off(p)>0);return items.length?[{...c,slug,items,max:Math.max(...items.map(off))}]:[]});
function useMidnight(){const [time,setTime]=useState<string[]>(['--','--','--']);useEffect(()=>{const tick=()=>{const now=new Date();const midnight=new Date(now);midnight.setHours(24,0,0,0);const seconds=Math.max(0,Math.floor((midnight.getTime()-now.getTime())/1000));setTime([Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(v=>String(v).padStart(2,'0')))};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[]);return time}
export function OffersPage(){const [tab,setTab]=useState('All deals');const time=useMidnight();const selected=groups.find(g=>g.name===tab)??groups[0];return <PageShell className="spc-page ofr-page"><ShopTopBar title="Offers & deals" subtitle={`${deals.length} products on sale`}/><div className="spc-wrap"><ShopTitle title="Offers & deals" section="Offers" count={`${deals.length} products on sale`}/><section className="spc-hero ofr-hero"><div className="spc-hero-copy"><span className="ofr-limited">LIMITED TIME</span><h1>Big savings for little ones</h1><p>Up to {maxOff}% off top baby brands</p><Button variant="ghost" asChild className="ofr-shop-flash"><a href="#ofr-flash">Shop flash deals <ArrowRight/></a></Button></div><ShopHeroPhotos items={flash}/></section><section className="ofr-flash" id="ofr-flash"><div className="ofr-flash-head"><div><span className="ofr-flash-eyebrow"><Zap/>TODAY’S LITTLE SAVINGS</span><h2>Flash deals</h2><p>Time left today</p></div><div className="ofr-clock" aria-label="Time until local midnight">{time.map((v,i)=><div key={i}><strong>{v}</strong><small>{['Hours','Minutes','Seconds'][i]}</small></div>)}</div></div><div className="ofr-flash-grid">{flash.map((p,i)=><ShopProductCard product={p} key={p.slug} tint={i} variant="rail"><div className="ofr-saving"><span>Save ৳ {tk(p.old-p.price)}</span><progress max={100} value={Math.min(100,off(p)*3)} aria-label={`${off(p)}% discount`}/></div></ShopProductCard>)}</div></section><nav className="spc-chip-row ofr-tabs" aria-label="Deal groups">{groups.map(g=><Button variant="ghost" key={g.name} className={`spc-chip ${tab===g.name?'spc-on':''}`} aria-pressed={tab===g.name} onClick={()=>setTab(g.name)}>{g.name} <span>({g.items.length})</span></Button>)}</nav><ShopSection eyebrow="REAL SAVINGS, LITTLE PRICES" title={selected?.name??'All deals'}><span className="ofr-count" aria-live="polite">{selected?.items.length??0} deals</span></ShopSection><div className="spc-grid">{selected?.items.map((p,i)=><ShopProductCard key={p.slug} product={p} tint={i}/>)}</div><ShopSection eyebrow="FIND YOUR FAVOURITES" title="Shop deals by category"/><div className="ofr-category-grid">{categoryDeals.map((c,i)=><Link to="/categories/$cat" params={{cat:c.slug}} key={c.slug} className={`ofr-category spc-tint-${i%7}`}><div className="ofr-category-art"><img src={c.items[0]?.image} alt=""/></div><strong>{c.name}</strong><span>{c.items.length} deals · up to {c.max}%</span><span className="ofr-category-link">Shop deals <ArrowRight/></span></Link>)}</div><section className="ofr-promise"><Truck/><div><h2>Free delivery on orders over ৳3,000</h2><p>Cash on delivery all over Bangladesh</p></div></section></div><MobileTabBar/></PageShell>}
