import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { Truck, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageShell, MobileTabBar } from './page-shell';
import { ShopProductCard, ShopTopBar, ShopTitle, ShopSection, ShopHeroPhotos } from './shop-product-card';
import { products, off, tk } from '@/lib/products';
import { catalogCategories } from '@/lib/catalog-demo';
import { getCategoryListing } from '@/lib/home-categories';
import { slugify } from '@/lib/live-head';
const deals=products.filter(p=>off(p)>0).sort((a,b)=>off(b)-off(a));const flash=deals.slice(0,8);const maxOff=Math.max(0,...deals.map(off));const maxSavings=Math.max(0,...deals.map(p=>p.old-p.price));
const groups=[{name:'All deals',items:deals},{name:'Top deals',items:flash},{name:'Under ৳500',items:deals.filter(p=>p.price<500)},{name:'Bundles & gift sets',items:deals.filter(p=>/gift|set|pack/i.test(`${p.name} ${p.type??''}`))},{name:'Big savings',items:deals.filter(p=>p.old-p.price>=400).sort((a,b)=>(b.old-b.price)-(a.old-a.price))},{name:'New arrivals on sale',items:deals.filter(p=>/new/i.test(p.badge??''))}].filter(g=>g.items.length);
const categoryDeals=catalogCategories.flatMap(c=>{const slug=slugify(c.name);const items=getCategoryListing(slug).items.filter(p=>off(p)>0);return items.length?[{...c,slug,items,max:Math.max(...items.map(off))}]:[]});
export function OffersPage(){const [tab,setTab]=useState('All deals');const [limit,setLimit]=useState(12);const selected=groups.find(g=>g.name===tab)??groups[0];const items=selected?.items??[];return <PageShell className="spc-page ofr-page"><ShopTopBar title="Offers & deals" subtitle={`${deals.length} products on sale`}/><div className="spc-wrap"><ShopTitle title="Offers & deals" section="Offers" count={`${deals.length} products on sale`}/><section className="spc-hero ofr-hero"><div className="spc-hero-copy"><span className="spc-eyebrow">EVERYDAY LITTLE SAVINGS</span><h2>Big savings for little ones</h2><p>Up to {maxOff}% off top baby brands</p><Button variant="ghost" asChild className="ofr-shop-flash"><a href="#ofr-flash">Explore top deals <ArrowRight/></a></Button></div><ShopHeroPhotos items={flash}/></section><section className="ofr-flash" id="ofr-flash"><div className="ofr-flash-head"><div><span className="ofr-flash-eyebrow">REAL SAVINGS</span><h2>Today's top deals</h2><p>{deals.length} products on sale · save up to ৳{tk(maxSavings)}</p></div></div><div className="ofr-flash-grid">{flash.map((p,i)=><ShopProductCard product={p} key={p.slug} tint={i} variant="rail"><p className="ofr-saving">You save ৳{tk(p.old-p.price)}</p></ShopProductCard>)}</div></section><nav className="spc-chip-row ofr-tabs" aria-label="Deal groups">{groups.map(g=><Button variant="ghost" key={g.name} className={`spc-chip ${tab===g.name?'spc-on':''}`} aria-pressed={tab===g.name} onClick={()=>{setTab(g.name);setLimit(12)}}>{g.name} <span>({g.items.length})</span></Button>)}</nav><ShopSection eyebrow="REAL SAVINGS, LITTLE PRICES" title={selected?.name??'All deals'}><span className="ofr-count" aria-live="polite">{Math.min(limit,items.length)} of {items.length}</span></ShopSection><div className="spc-grid ofr-main-grid">{items.slice(0,limit).map((p,i)=><ShopProductCard key={p.slug} product={p} tint={i}/>)}</div>{limit<items.length&&<Button variant="ghost" className="spc-primary ofr-more" onClick={()=>setLimit(n=>n+12)}>Show more deals <ArrowRight/></Button>}<ShopSection eyebrow="FIND YOUR FAVOURITES" title="Shop deals by category"/><p className="ofr-note">Some products appear in more than one category</p><div className="ofr-category-grid">{categoryDeals.map((c,i)=>{const content=<><div className="ofr-category-art"><img src={c.image.url} alt=""/></div><strong>{c.name}</strong><span>{c.items.length} deals · up to {c.max}%</span><span className="ofr-category-link">Shop deals <ArrowRight/></span></>;return c.slug==='baby-clothing'?<Link to="/categories/baby-clothing" key={c.slug} className={`ofr-category spc-tint-${i%7}`}>{content}</Link>:<Link to="/categories/$cat" params={{cat:c.slug}} key={c.slug} className={`ofr-category spc-tint-${i%7}`}>{content}</Link>})}</div><section className="ofr-promise"><Truck/><div><h2>Free delivery on orders over ৳3,000</h2><p>Cash on delivery · usually 2–4 days across Bangladesh</p></div></section></div><MobileTabBar/></PageShell>}
