import type { ReactNode } from 'react';
import { Link, useNavigate } from '@tanstack/react-router';
import { ArrowLeft, ShoppingCart, Heart, Plus, Minus, Grid2X2, List, Star, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useCart } from '@/lib/cart-store';
import { off, products, tk, type Product } from '@/lib/products';
export const popularProducts = [...products].sort((a,b)=>b.reviews-a.reviews);
export function ShopProductCard({product:p,tint=0,variant='grid',children,onWish}:{product:Product;tint?:number|undefined;variant?:'grid'|'list'|'rail'|undefined;children?:ReactNode;onWish?:()=>void}) {
 const {lines,wish,add,setQty,toggleWish}=useCart(); const line=lines.find(l=>l.slug===p.slug); const qty=line?.qty??0; const saved=wish.includes(p.slug);
 return <article className={`spc-card spc-${variant} spc-tint-${tint%7}`}><div className="spc-art"><Link to="/product/$slug" params={{slug:p.slug}} className="spc-photo" tabIndex={-1} aria-hidden="true"><img src={p.image} alt="" loading="lazy"/></Link>{off(p)>0&&<span className="spc-discount">-{off(p)}%</span>}<Button variant="ghost" className="spc-heart" aria-label={`${saved?'Remove':'Save'} ${p.name} ${saved?'from':'to'} wishlist`} aria-pressed={saved} onClick={()=>onWish?onWish():toggleWish(p.slug)}><Heart className={saved?'spc-saved':''}/></Button></div><div className="spc-info"><span className="spc-brand">{p.brand}</span><h3><Link to="/product/$slug" params={{slug:p.slug}}>{p.name}</Link></h3><span className="spc-size">{p.sizes.length>3?`${p.sizes[0]} – ${p.sizes.at(-1)}`:p.sizes.join(' · ')}</span><span className="spc-rating"><Star/>{p.rating.toFixed(1)} <small>({p.reviews})</small></span><div className="spc-foot"><div className="spc-price"><strong>৳ {tk(p.price)}</strong>{p.old>p.price&&<del>৳ {tk(p.old)}</del>}</div>{qty? <div className="spc-stepper"><Button variant="ghost" aria-label={`Remove one ${p.name}`} onClick={()=>{if(line)setQty(line.slug,line.size,qty-1)}}><Minus/></Button><span aria-live="polite">{qty}</span><Button variant="ghost" aria-label={`Add one more ${p.name}`} onClick={e=>add(p,line?.size,1,e.currentTarget)}><Plus/></Button></div>:<Button variant="ghost" className="spc-add" aria-label={`Add ${p.name} to cart`} onClick={e=>add(p,undefined,1,e.currentTarget)}><Plus/><span>Add to cart</span></Button>}</div>{children}</div></article>
}
export function ShopTopBar({title,subtitle,children}:{title:string;subtitle:string;children?:ReactNode}) {const navigate=useNavigate();const {lines}=useCart();const n=lines.reduce((s,l)=>s+l.qty,0);return <header className="spc-top"><Button variant="ghost" className="spc-icon" aria-label="Go back" onClick={()=>{if(window.history.length>1)window.history.back();else void navigate({to:'/'})}}><ArrowLeft/></Button>{children??<div className="spc-top-text"><h2>{title}</h2><p>{subtitle}</p></div>}<Button variant="ghost" asChild className="spc-icon spc-cart"><Link to="/cart" aria-label={`Cart, ${n} items`}><ShoppingCart/><span aria-live="polite">{n}</span></Link></Button></header>}
export function ShopTitle({title,section,count}:{title:string;section:string;count?:string}) {return <div className="spc-desktop-title"><nav aria-label="Breadcrumb"><Link to="/">Home</Link><span>›</span>{section}</nav><div><h1>{title}</h1><p aria-live="polite">{count}</p></div></div>}
export function ShopViewToggle({list,setList}:{list:boolean;setList:(v:boolean)=>void}){return <div className="spc-toggle"><Button variant="ghost" aria-label="Grid view" aria-pressed={!list} className={!list?'spc-on':''} onClick={()=>setList(false)}><Grid2X2/></Button><Button variant="ghost" aria-label="List view" aria-pressed={list} className={list?'spc-on':''} onClick={()=>setList(true)}><List/></Button></div>}
export function ShopSection({eyebrow,title,children}:{eyebrow:string;title:string;children?:ReactNode}){return <div className="spc-section-head"><div><span className="spc-eyebrow">{eyebrow}</span><h2>{title}</h2></div>{children}</div>}
export function ShopHeroPhotos({items}:{items:Product[]}){return <div className="spc-hero-art" aria-hidden="true">{items.slice(0,3).map((p,i)=><div className={`spc-float spc-float-${i}`} key={p.slug}><img src={p.image} alt=""/></div>)}</div>}
export function ShopEmpty({kind,title,text,children}:{kind:'heart'|'search';title:string;text:string;children?:ReactNode}){return <section className="spc-empty"><svg className="spc-illustration" viewBox="0 0 160 120" aria-hidden="true"><rect x="20" y="20" width="120" height="88" rx="30" className="spc-illustration-bg"/>{kind==='heart'?<path d="M80 89 49 61C25 36 61 20 80 43c19-23 55-7 31 18Z" className="spc-illustration-pink"/>:<g className="spc-illustration-stroke"><circle cx="73" cy="57" r="25"/><path d="m92 76 23 23M60 58h26"/></g>}<circle cx="130" cy="25" r="7" className="spc-illustration-pink"/></svg><h2>{title}</h2><p>{text}</p><div className="spc-empty-actions">{children}</div></section>}
export function ShopRail({items=popularProducts.slice(0,8)}:{items?:Product[]}){return <div className="spc-rail-grid">{items.map((p,i)=><ShopProductCard key={p.slug} product={p} tint={i} variant="rail"/>)}</div>}
export function ShopBrowseLinks(){return <><Button variant="ghost" asChild className="spc-primary"><Link to="/trending">Start shopping <ArrowRight/></Link></Button><Link to="/categories" className="spc-text-link">Browse categories</Link></>}
