import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, Star, Trophy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageShell, MobileTabBar } from './page-shell';
import { ShopProductCard, ShopTopBar, ShopTitle, ShopSection, ShopHeroPhotos, popularProducts } from './shop-product-card';
import { products, off } from '@/lib/products';
import { slugify } from '@/lib/live-head';
const rankings={'Most loved':popularProducts,'Top rated':[...products].sort((a,b)=>b.rating-a.rating||b.reviews-a.reviews),'Best value':[...products].sort((a,b)=>off(b)-off(a)||b.reviews-a.reviews)};
const avg=products.reduce((s,p)=>s+p.rating,0)/products.length;
const brands=[...new Set(products.map(p=>p.brand))].map(brand=>{const items=products.filter(p=>p.brand===brand);return {brand,count:items.length,avg:items.reduce((s,p)=>s+p.rating,0)/items.length,reviews:items.reduce((s,p)=>s+p.reviews,0)}}).sort((a,b)=>b.reviews-a.reviews);
const catSlugs:Record<string,string>={'Diapers':'diapers-and-wipes','Bath & Skin':'bath-and-hygiene','Feeding':'feeding-and-nursing','Clothing':'baby-clothing','Toys':'toys-and-learning','Baby Care':'baby-accessories','Health':'health-and-safety'};
export function TrendingPage(){const [tab,setTab]=useState<keyof typeof rankings>('Most loved');const [limit,setLimit]=useState(12);return <PageShell className="spc-page trd-page"><ShopTopBar title="Trending now" subtitle="Most loved by parents"/><div className="spc-wrap"><ShopTitle title="Trending now" section="Trending" count="Most loved by parents"/><div className="trd-intro"><section className="spc-hero trd-hero"><div className="spc-hero-copy"><span className="spc-eyebrow">WHAT PARENTS ARE BUYING</span><h2>Trending this week</h2><p>{products.length} products · average rating {avg.toFixed(1)}★</p></div><ShopHeroPhotos items={popularProducts}/></section><section className="trd-podium"><ShopSection eyebrow="THE LITTLE LEADERS" title="Top 3"><Trophy/></ShopSection><div className="trd-podium-grid">{popularProducts.slice(0,3).map((p,i)=><div key={p.slug} className={`trd-rank trd-rank-${i}`}><span className="trd-rank-number">{i+1}</span><ShopProductCard product={p} tint={i}/><span className="trd-review-count"><Star/>{p.reviews} reviews</span></div>)}</div></section></div><div className="spc-chip-row trd-tabs" role="group" aria-label="Trending ranking">{(Object.keys(rankings) as (keyof typeof rankings)[]).map(t=><Button variant="ghost" className={`spc-chip ${tab===t?'spc-on':''}`} aria-pressed={tab===t} key={t} onClick={()=>{setTab(t);setLimit(12)}}>{t}</Button>)}</div><ShopSection eyebrow="CHOSEN BY PARENTS" title={tab}><span className="trd-count" aria-live="polite">{Math.min(limit,products.length)} of {products.length}</span></ShopSection><div className="spc-grid">{rankings[tab].slice(0,limit).map((p,i)=><ShopProductCard key={p.slug} product={p} tint={i}/>)}</div>{limit<products.length&&<div className="trd-more"><Button variant="ghost" className="spc-primary" onClick={()=>setLimit(products.length)}>Show more <ArrowRight/></Button></div>}<ShopSection eyebrow="TRUSTED LITTLE FAVOURITES" title="Trending brands"/><div className="trd-brands">{brands.map((b,i)=><Link key={b.brand} to="/brands/$brand" params={{brand:slugify(b.brand.normalize('NFD').replace(/[\u0300-\u036f]/g,''))}} className={`trd-brand spc-tint-${i%7}`}><span className="trd-brand-mark">{b.brand.slice(0,1)}</span><h3>{b.brand}</h3><p>{b.count} products · {b.avg.toFixed(1)}★</p><ArrowRight/></Link>)}</div><ShopSection eyebrow="EXPLORE MORE" title="Trending categories"/><div className="trd-categories">{Object.entries(catSlugs).map(([name,cat])=>{const count=products.filter(p=>p.category===name).length;return count>0?<Link to="/categories/$cat" params={{cat}} key={cat} className="spc-chip">{name} ({count}) <ArrowRight/></Link>:null})}</div></div><MobileTabBar active="categories"/></PageShell>}
