import { useEffect, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, ShoppingCart, Trash2, Check, Heart } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageShell, MobileTabBar } from './page-shell';
import { ShopProductCard, ShopTopBar, ShopTitle, ShopViewToggle, ShopSection, ShopEmpty, ShopRail, ShopBrowseLinks } from './shop-product-card';
import { useCart, FREE_DELIVERY } from '@/lib/cart-store';
import { getProduct, off, products, tk, type Product } from '@/lib/products';
type Undo={product:Product;move:boolean;size:string};
export function WishlistPage(){
 const {wish,lines,add,setQty,toggleWish,clearWish,moveAllToCart}=useCart();const [sort,setSort]=useState('Recently saved');const [list,setList]=useState(false);const [confirm,setConfirm]=useState(false);const [undo,setUndo]=useState<Undo|null>(null);
 useEffect(()=>{if(!undo)return;const timer=setTimeout(()=>setUndo(null),5000);return()=>clearTimeout(timer)},[undo]);
 const saved=wish.map(getProduct).filter((p):p is Product=>!!p);const items=[...saved].sort((a,b)=>sort==='Price low → high'?a.price-b.price:sort==='Price high → low'?b.price-a.price:sort==='Biggest discount'?off(b)-off(a):0);const total=saved.reduce((s,p)=>s+p.price,0);const saving=saved.reduce((s,p)=>s+Math.max(0,p.old-p.price),0);const related=products.filter(p=>saved.some(x=>x.category===p.category)&&!wish.includes(p.slug)).sort((a,b)=>b.reviews-a.reviews).slice(0,4);
 const removeItem=(p:Product,move=false,origin?:HTMLElement)=>{const size=p.sizes[0]??'';if(move)add(p,size,1,origin);toggleWish(p.slug);setUndo({product:p,move,size})};
 const restore=()=>{if(!undo)return;if(!wish.includes(undo.product.slug))toggleWish(undo.product.slug);if(undo.move){const line=lines.find(l=>l.slug===undo.product.slug&&l.size===undo.size);if(line)setQty(line.slug,line.size,line.qty-1)}setUndo(null)};
 const summary=<aside className="wsh-summary"><span className="spc-eyebrow">SAVED FOR YOUR LITTLE ONE</span><h2>৳ {tk(total)}</h2><p>{items.length} saved items · Save ৳ {tk(saving)}</p><progress className="wsh-progress" max={FREE_DELIVERY} value={Math.min(total,FREE_DELIVERY)} aria-label="Progress towards free delivery"/><p className="wsh-delivery">{total>=FREE_DELIVERY?'Free delivery on these':`Add ৳ ${tk(FREE_DELIVERY-total)} more for free delivery`}</p><div className="wsh-bulk"><Button variant="ghost" className="wsh-move-all" disabled={!items.length} onClick={()=>{moveAllToCart();setUndo(null)}}><ShoppingCart/>Move all to cart</Button><Button variant="ghost" className="wsh-clear" disabled={!items.length} onClick={()=>setConfirm(true)}>Clear all</Button></div>{confirm&&<div className="wsh-confirm" role="alert"><p>Remove all {items.length} saved items?</p><Button variant="ghost" className="wsh-clear" onClick={()=>{clearWish();setConfirm(false);setUndo(null)}}>Yes, clear wishlist</Button><Button variant="ghost" className="wsh-clear" onClick={()=>setConfirm(false)}>Keep items</Button></div>}</aside>;
 return <PageShell className="spc-page wsh-page"><ShopTopBar title="My wishlist" subtitle={`${items.length} saved items`}/><div className="spc-wrap"><ShopTitle title="My wishlist" section="Wishlist" count={`${items.length} saved items`}/>{items.length?<div className="wsh-body">{summary}<div className="wsh-items"><div className="spc-toolbar"><label className="spc-sort"><span className="wsh-sort-label">Sort</span><select aria-label="Sort wishlist" value={sort} onChange={e=>setSort(e.target.value)}>{['Recently saved','Price low → high','Price high → low','Biggest discount'].map(s=><option key={s}>{s}</option>)}</select></label><ShopViewToggle list={list} setList={setList}/></div><div className={`spc-grid wsh-grid ${list?'spc-list-grid':''}`}>{items.map((p,i)=><ShopProductCard product={p} key={p.slug} tint={i} variant={list?'list':'grid'} onWish={()=>removeItem(p)}><div className="wsh-item-actions">{list&&lines.some(l=>l.slug===p.slug)&&<span className="wsh-in-cart"><Check/>In cart</span>}<Button variant="ghost" className="wsh-move" onClick={e=>removeItem(p,true,e.currentTarget)}><ShoppingCart/>Move to cart</Button><Button variant="ghost" className="wsh-remove" aria-label={`Remove ${p.name} from wishlist`} onClick={()=>removeItem(p)}><Trash2/></Button></div></ShopProductCard>)}</div></div></div>:<><ShopEmpty kind="heart" title="Your wishlist is empty" text="Tap the heart on any product to save it for later."><ShopBrowseLinks/></ShopEmpty><ShopSection eyebrow="LITTLE FAVOURITES" title="Parents love these"/><ShopRail/></>}{items.length>0&&related.length>0&&<section className="wsh-recommendations"><ShopSection eyebrow="MORE LITTLE FAVOURITES" title="You may also like"><Heart/></ShopSection><ShopRail items={related}/></section>}</div>{undo&&<div className="wsh-snackbar" role="status"><span>{undo.move?'Moved to cart':'Removed'} {undo.product.name}</span><Button variant="ghost" onClick={restore}>Undo</Button></div>}<MobileTabBar/></PageShell>
}
