import { useState, type ReactNode } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, ChevronRight, CreditCard, FileText, House, Info, LockKeyhole, MapPin, Minus, Pencil, Phone, Plus, ReceiptText, ShieldCheck, ShoppingCart, Tag, Trash2, Truck, UserRound, Building2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DemoControl } from "@/components/shop-navigation";
import { ShoppingShell, ShoppingCTA } from "@/components/shopping-reference";
import { shoppingImage, shoppingProducts } from "@/lib/shopping-demo";

export function CheckoutSteps({step}:{step:number}) {return <ol className="co-steps">{["Checkout","Address","Payment","Confirm"].map((s,i)=><li key={s} className={`${i+1===step?"current":""} ${i+1<step?"complete":""}`}><span>{i+1<step&&step===2?<Check/>:i+1}</span><b>{s}</b></li>)}</ol>;}
function Panel({title,icon,action,children}:{title:string;icon:ReactNode;action?:ReactNode;children:ReactNode}){return <section className="co-panel"><header><i>{icon}</i><h2>{title}</h2>{action}</header>{children}</section>;}
const cartItems=[{id:1,size:"500ml",qty:1},{id:0,size:"Size: M",qty:2},{id:4,size:"120 pcs",qty:1}];
function ItemRows({review=false}:{review?:boolean}){return <div className="co-items">{cartItems.map(({id,size,qty})=>{const p=shoppingProducts[id];if(!p)return null;return <div className="co-item" key={id}><img src={shoppingImage(`next-${p.id}`)} alt={p.name}/><div><small>{id===0?"Pampers":"Johnson’s"}</small><h3>{id===0?"New Baby Diapers":id===1?"Baby Shampoo":"Baby Wipes"}</h3><p>{id===0?"Soft & Dry":id===1?"(No More Tears)":"Extra Gentle"}</p><small>{size}</small></div><div className="co-item-price"><strong>৳ {p.price}</strong><del>৳ {p.old}</del></div>{review?<p className="co-review-qty">Qty: {qty}</p>:<div className="co-quantity"><DemoControl label="Decrease quantity"><Minus/></DemoControl><b>{qty}</b><DemoControl label="Increase quantity"><Plus/></DemoControl></div>}</div>;})}</div>;}
function Summary(){return <Panel title="Order Summary" icon={<ReceiptText/>}><dl className="co-summary"><div><dt>Subtotal (3 items)</dt><dd>৳ 3,320</dd></div><div className="pink"><dt>Product Discount</dt><dd>- ৳ 610</dd></div><div><dt>Coupon Discount</dt><dd>- ৳ 0</dd></div><div><dt>Delivery Charge <Info/></dt><dd>৳ 80</dd></div><div className="total"><dt>Total Amount</dt><dd>৳ 2,790</dd></div></dl></Panel>;}
function EditLink({to,label="Edit"}:{to:"/trending"|"/checkout"|"/checkout/address"|"/checkout/payment"|"/checkout/address/new";label?:string}){return <Button variant="ghost" asChild className="co-edit"><Link to={to}>{label==="Edit"&&<Pencil/>}{label}{label!=="Edit"&&<ChevronRight/>}</Link></Button>;}
export function CheckoutReference(){return <ShoppingShell crumb="Checkout" title="Checkout" className="co-screen"><p className="co-subtitle">Review your items and continue to the next step.</p><CheckoutSteps step={1}/><Panel title="Your Items (3)" icon={<ShoppingCart/>} action={<EditLink to="/trending" label="Edit Cart"/>}><ItemRows/></Panel><div className="co-coupon"><Tag/><div><h3>Have a Coupon Code?</h3><p>Enter your coupon code to get a discount</p></div><input aria-label="Coupon code" placeholder="Enter coupon code"/><DemoControl label="Apply coupon">Apply</DemoControl></div><Summary/><div className="co-free"><Truck/><div><p>You’re just <em>৳ 210</em> away from FREE delivery!</p><progress max="100" value="75"/></div></div><ShoppingCTA to="/checkout/address">Continue to Address</ShoppingCTA></ShoppingShell>;}
const addresses=[{name:"Home",image:"home-address-art",line1:"House 25, Road 10, Dhanmondi,",line2:"Dhaka 1209, Bangladesh"},{name:"Office",image:"office-address-art",line1:"Level 8, Navana Tower,",line2:"Gulshan 1, Dhaka 1212"},{name:"Others",image:"other-address-art",line1:"House 12, Block C, Mirpur 10,",line2:"Dhaka 1216"}];
export function AddressReference(){const [selected,setSelected]=useState("Home");return <ShoppingShell crumb="Checkout" title="Address Selection" className="co-screen co-address"><p className="co-subtitle">Choose a delivery address for your order.</p><CheckoutSteps step={2}/><Panel title="Saved Addresses" icon={<MapPin/>}><div className="co-addresses">{addresses.map((a,i)=><article className={selected===a.name?"selected":""} key={a.name}><input type="radio" name="address" aria-label={a.name} checked={selected===a.name} onChange={()=>setSelected(a.name)}/><img src={shoppingImage(a.image)} alt=""/><div><h3>{a.name}{i===0&&<span>Default</span>}</h3><p>{a.line1}<br/>{a.line2}<br/>+880 1712 345678</p></div><div className="co-address-actions"><EditLink to="/checkout/address/new"/>{i>0&&<DemoControl label={`Delete ${a.name}`}><Trash2/>Delete</DemoControl>}</div></article>)}</div></Panel><Button asChild variant="ghost" className="co-new-address"><Link to="/checkout/address/new"><i><Plus/></i><div><h2>Add New Address</h2><p>Add a new delivery address to your account</p></div><ChevronRight/></Link></Button><div className="co-delivery"><img src={shoppingImage("delivery-art")} alt="Purple delivery truck"/><div><h3>Fast & Safe Delivery</h3><p>We deliver your baby care products safely<br/>to your doorstep across Bangladesh.</p></div></div><ShoppingCTA to="/checkout/payment">Continue to Payment</ShoppingCTA></ShoppingShell>;}
export function NewAddressReference(){const [type,setType]=useState("Home");const [full,setFull]=useState("");const [notes,setNotes]=useState("");return <ShoppingShell crumb="Checkout › Add New Address" title="Add New Address" className="co-screen co-new"><p className="co-subtitle">Enter your delivery address details.</p><CheckoutSteps step={2}/><Panel title="Address Details" icon={<MapPin/>}><form className="co-form" onSubmit={e=>e.preventDefault()}><label>Full Name <em>*</em><span><UserRound/><input placeholder="Enter full name" aria-label="Full Name"/></span></label><label>Phone Number <em>*</em><span><Phone/><input type="tel" placeholder="Enter phone number" aria-label="Phone Number"/></span></label><div className="co-form-pair"><label>District <em>*</em><span><MapPin/><select aria-label="District" defaultValue=""><option value="" disabled>Select District</option><option>Dhaka</option></select></span></label><label>Area / Thana <em>*</em><span><MapPin/><select aria-label="Area / Thana" defaultValue=""><option value="" disabled>Select Area</option><option>Dhanmondi</option><option>Gulshan</option><option>Mirpur</option></select></span></label></div><label>Full Address <em>*</em><span className="textarea"><House/><textarea aria-label="Full Address" placeholder="House, Road, Block, etc." maxLength={200} value={full} onChange={e=>setFull(e.target.value)}/></span><small>{full.length}/200</small></label><fieldset><legend>Address Type <em>*</em></legend><div>{[House,Building2,MapPin].map((Icon,i)=>{const name=["Home","Office","Others"][i]??"Home";return <label key={name} className={type===name?"selected":""}><input type="radio" name="address-type" checked={type===name} onChange={()=>setType(name)}/><Icon/>{name}</label>;})}</div></fieldset><label>Delivery Instructions (Optional)<span className="textarea"><FileText/><textarea aria-label="Delivery Instructions" placeholder="e.g. Near the mosque, House is blue color, Call before delivery, etc." maxLength={200} value={notes} onChange={e=>setNotes(e.target.value)}/></span><small>{notes.length}/200</small></label></form></Panel><ShoppingCTA to="/checkout/address">Save Address</ShoppingCTA></ShoppingShell>;}
const payments=[{name:"Cash on Delivery",image:"cod-art",desc:"Pay when you receive your order at your doorstep."},{name:"bKash",image:"bkash-art",desc:"Pay securely with bKash."},{name:"Nagad",image:"nagad-art",desc:"Pay securely with Nagad."},{name:"Credit / Debit Card",desc:"Visa, Mastercard, AMEX"}];
export function PaymentReference(){const [method,setMethod]=useState("Cash on Delivery");return <ShoppingShell crumb="Checkout › Payment Method" title="Payment Method" className="co-screen co-payment"><p className="co-subtitle">Choose your preferred payment method.</p><CheckoutSteps step={3}/><div className="co-payments">{payments.map((m,i)=><label key={m.name} className={method===m.name?"selected":""}><input type="radio" name="payment" checked={method===m.name} onChange={()=>setMethod(m.name)}/>{m.image?<img src={shoppingImage(m.image)} alt=""/>:<CreditCard/>}<div><h3>{m.name}</h3><p>{m.desc}</p></div>{i===0?<span>Recommended</span>:<ChevronRight/>}</label>)}</div><div className="co-cod-info"><img src={shoppingImage("parcel-art")} alt="Parcel"/><div><h3>Cash on Delivery Information</h3>{["Pay with cash when you receive your order","No extra charges","Available across Bangladesh"].map(t=><p key={t}><Check/>{t}</p>)}</div></div><div className="co-secure"><ShieldCheck/><div><h3>100% Secure Payment</h3><p>Your payment information is always safe<br/>and secure with us.</p></div></div><ShoppingCTA to="/checkout/review">Continue to Review</ShoppingCTA></ShoppingShell>;}
export function ReviewReference(){const [agree,setAgree]=useState(true);return <ShoppingShell crumb="Checkout › Order Review & Confirm" title="Order Review & Confirm" className="co-screen co-review"><p className="co-subtitle">Please review your order details before placing it.</p><CheckoutSteps step={4}/><Panel title="Delivery Address" icon={<MapPin/>} action={<EditLink to="/checkout/address"/>}><div className="co-review-address"><img src={shoppingImage("home-address-art")} alt="Home"/><div><h3>Home <span>Default</span></h3><p>House 25, Road 10, Dhanmondi,<br/>Dhaka 1209, Bangladesh<br/>+880 1712 345678</p></div></div></Panel><Panel title="Order Items (3)" icon={<ShoppingCart/>} action={<EditLink to="/checkout" label="Edit Cart"/>}><ItemRows review/></Panel><Panel title="Payment Method" icon={<CreditCard/>} action={<EditLink to="/checkout/payment"/>}><div className="co-review-payment"><img src={shoppingImage("cod-art")} alt=""/><div><h3>Cash on Delivery</h3><p>Pay when you receive your order</p></div><ChevronRight/></div></Panel><Summary/><label className="co-terms"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/>I agree to the <span>Terms & Conditions</span> and <span>Privacy Policy</span></label><DemoControl label="Place Order" className="sr-cta"><LockKeyhole/>Place Order<ArrowRight/></DemoControl></ShoppingShell>;}
