import { useState, type ReactNode } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { toast } from "sonner";
import { ArrowRight, Check, ChevronRight, CreditCard, FileText, House, Info, LockKeyhole, MapPin, Minus, Pencil, Phone, Plus, ReceiptText, ShieldCheck, ShoppingCart, Tag, Trash2, Truck, UserRound, Building2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ShoppingShell, ShoppingCTA } from "@/components/shopping-reference";
import { ProductLink } from "@/components/live";
import { shoppingImage } from "@/lib/shopping-demo";
import { FREE_DELIVERY, totals, useCart, type CartLine } from "@/lib/cart-store";
import { getProduct, tk } from "@/lib/products";

export function CheckoutSteps({step}:{step:number}) {return <ol className="co-steps">{["Checkout","Address","Payment","Confirm"].map((s,i)=><li key={s} className={`${i+1===step?"current":""} ${i+1<step?"complete":""}`}><span>{i+1<step?<Check/>:i+1}</span><b>{s}</b></li>)}</ol>;}
export function Panel({title,icon,action,children}:{title:string;icon:ReactNode;action?:ReactNode;children:ReactNode}){return <section className="co-panel"><header><i>{icon}</i><h2>{title}</h2>{action}</header>{children}</section>;}

export function ItemRows({lines,review=false}:{lines:CartLine[];review?:boolean}){
  const {setQty,remove}=useCart();
  return <div className="co-items">{lines.map(({slug,size,qty})=>{const p=getProduct(slug);if(!p)return null;return <div className="co-item" key={slug+size}><ProductLink slug={slug}><img src={p.image} alt={p.name}/></ProductLink><div><small>{p.brand}</small><h3><ProductLink slug={slug}>{p.name}</ProductLink></h3><p>{p.sub}</p><small>Size: {size}</small></div><div className="co-item-price"><strong>৳ {tk(p.price*qty)}</strong><del>৳ {tk(p.old*qty)}</del></div>{review?<p className="co-review-qty">Qty: {qty}</p>:<div className="co-quantity"><Button type="button" variant="ghost" className="demo-button" aria-label="Decrease quantity" onClick={()=>setQty(slug,size,qty-1)}><Minus/></Button><b>{qty}</b><Button type="button" variant="ghost" className="demo-button" aria-label="Increase quantity" onClick={()=>setQty(slug,size,qty+1)}><Plus/></Button><Button type="button" variant="ghost" className="demo-button lv-remove" aria-label={`Remove ${p.name}`} onClick={()=>remove(slug,size)}><Trash2/></Button></div>}</div>;})}</div>;
}
export function Summary({lines}:{lines:CartLine[]}){const t=totals(lines);return <Panel title="Order Summary" icon={<ReceiptText/>}><dl className="co-summary"><div><dt>Subtotal ({t.count} items)</dt><dd>৳ {tk(t.subtotal)}</dd></div><div className="pink"><dt>Product Discount</dt><dd>- ৳ {tk(t.discount)}</dd></div><div><dt>Coupon Discount</dt><dd>- ৳ 0</dd></div><div><dt>Delivery Charge <Info/></dt><dd>{t.delivery?`৳ ${t.delivery}`:"FREE"}</dd></div><div className="total"><dt>Total Amount</dt><dd>৳ {tk(t.total)}</dd></div></dl></Panel>;}
export function FreeDelivery({lines}:{lines:CartLine[]}){const t=totals(lines);const left=FREE_DELIVERY-t.net;return <div className="co-free"><Truck/><div><p>{left>0?<>You’re just <em>৳ {tk(left)}</em> away from FREE delivery!</>:<>You’ve unlocked <em>FREE</em> delivery!</>}</p><progress max={FREE_DELIVERY} value={Math.min(FREE_DELIVERY,t.net)}/></div></div>;}
function EditLink({to,label="Edit"}:{to:"/cart"|"/checkout"|"/checkout/address"|"/checkout/payment"|"/checkout/address/new";label?:string}){return <Button variant="ghost" asChild className="co-edit"><Link to={to}>{label==="Edit"&&<Pencil/>}{label}{label!=="Edit"&&<ChevronRight/>}</Link></Button>;}
function EmptyNotice(){return <div className="lv-empty"><p>Your cart is empty.</p><ShoppingCTA to="/trending">Continue Shopping</ShoppingCTA></div>;}

export function CheckoutReference(){
  const {lines}=useCart();const [code,setCode]=useState("");
  return <ShoppingShell crumb="Checkout" title="Checkout" className="co-screen"><p className="co-subtitle">Review your items and continue to the next step.</p><CheckoutSteps step={1}/>{lines.length===0?<EmptyNotice/>:<><Panel title={`Your Items (${lines.length})`} icon={<ShoppingCart/>} action={<EditLink to="/cart" label="Edit Cart"/>}><ItemRows lines={lines}/></Panel><form className="co-coupon" onSubmit={e=>{e.preventDefault();toast.error(code.trim()?`Coupon “${code.trim()}” is not valid`:"Please enter a coupon code");}}><Tag/><div><h3>Have a Coupon Code?</h3><p>Enter your coupon code to get a discount</p></div><input aria-label="Coupon code" placeholder="Enter coupon code" value={code} onChange={e=>setCode(e.target.value)}/><Button type="submit" variant="ghost" className="demo-button">Apply</Button></form><Summary lines={lines}/><FreeDelivery lines={lines}/><ShoppingCTA to="/checkout/address">Continue to Address</ShoppingCTA></>}</ShoppingShell>;
}

export const addresses=[{name:"Home",image:"home-address-art",line1:"House 25, Road 10, Dhanmondi,",line2:"Dhaka 1209, Bangladesh"},{name:"Office",image:"office-address-art",line1:"Level 8, Navana Tower,",line2:"Gulshan 1, Dhaka 1212"},{name:"Others",image:"other-address-art",line1:"House 12, Block C, Mirpur 10,",line2:"Dhaka 1216"}];
export function AddressReference(){
  const {address,setAddress}=useCart();const [list,setList]=useState(addresses);
  return <ShoppingShell crumb="Checkout" title="Address Selection" className="co-screen co-address"><p className="co-subtitle">Choose a delivery address for your order.</p><CheckoutSteps step={2}/><Panel title="Saved Addresses" icon={<MapPin/>}><div className="co-addresses">{list.map((a,i)=><article className={address===a.name?"selected":""} key={a.name} onClick={()=>setAddress(a.name)}><input type="radio" name="address" aria-label={a.name} checked={address===a.name} onChange={()=>setAddress(a.name)}/><img src={shoppingImage(a.image)} alt=""/><div><h3>{a.name}{i===0&&<span>Default</span>}</h3><p>{a.line1}<br/>{a.line2}<br/>+880 1712 345678</p></div><div className="co-address-actions"><EditLink to="/checkout/address/new"/>{i>0&&<Button type="button" variant="ghost" className="demo-button" onClick={e=>{e.stopPropagation();setList(l=>l.filter(x=>x.name!==a.name));if(address===a.name)setAddress("Home");}}><Trash2/>Delete</Button>}</div></article>)}</div></Panel><Button asChild variant="ghost" className="co-new-address"><Link to="/checkout/address/new"><i><Plus/></i><div><h2>Add New Address</h2><p>Add a new delivery address to your account</p></div><ChevronRight/></Link></Button><div className="co-delivery"><img src={shoppingImage("delivery-art")} alt="Purple delivery truck"/><div><h3>Fast & Safe Delivery</h3><p>We deliver your baby care products safely<br/>to your doorstep across Bangladesh.</p></div></div><ShoppingCTA to="/checkout/payment">Continue to Payment</ShoppingCTA></ShoppingShell>;
}

export function NewAddressReference(){
  const navigate=useNavigate();const {setAddress}=useCart();
  const [type,setType]=useState("Home");const [full,setFull]=useState("");const [notes,setNotes]=useState("");const [name,setName]=useState("");const [phone,setPhone]=useState("");
  const save=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim()||!phone.trim()||!full.trim()){toast.error("Please fill in name, phone and full address");return;}setAddress(type);toast.success("Address saved");navigate({to:"/checkout/address"});};
  return <ShoppingShell crumb="Checkout › Add New Address" title="Add New Address" className="co-screen co-new"><p className="co-subtitle">Enter your delivery address details.</p><CheckoutSteps step={2}/><form onSubmit={save}><Panel title="Address Details" icon={<MapPin/>}><div className="co-form"><label>Full Name <em>*</em><span><UserRound/><input placeholder="Enter full name" aria-label="Full Name" value={name} onChange={e=>setName(e.target.value)}/></span></label><label>Phone Number <em>*</em><span><Phone/><input type="tel" placeholder="Enter phone number" aria-label="Phone Number" value={phone} onChange={e=>setPhone(e.target.value)}/></span></label><div className="co-form-pair"><label>District <em>*</em><span><MapPin/><select aria-label="District" defaultValue=""><option value="" disabled>Select District</option><option>Dhaka</option><option>Chattogram</option><option>Sylhet</option><option>Khulna</option></select></span></label><label>Area / Thana <em>*</em><span><MapPin/><select aria-label="Area / Thana" defaultValue=""><option value="" disabled>Select Area</option><option>Dhanmondi</option><option>Gulshan</option><option>Mirpur</option><option>Uttara</option></select></span></label></div><label>Full Address <em>*</em><span className="textarea"><House/><textarea aria-label="Full Address" placeholder="House, Road, Block, etc." maxLength={200} value={full} onChange={e=>setFull(e.target.value)}/></span><small>{full.length}/200</small></label><fieldset><legend>Address Type <em>*</em></legend><div>{[House,Building2,MapPin].map((Icon,i)=>{const n=["Home","Office","Others"][i]??"Home";return <label key={n} className={type===n?"selected":""}><input type="radio" name="address-type" checked={type===n} onChange={()=>setType(n)}/><Icon/>{n}</label>;})}</div></fieldset><label>Delivery Instructions (Optional)<span className="textarea"><FileText/><textarea aria-label="Delivery Instructions" placeholder="e.g. Near the mosque, House is blue color, Call before delivery, etc." maxLength={200} value={notes} onChange={e=>setNotes(e.target.value)}/></span><small>{notes.length}/200</small></label></div></Panel><Button type="submit" variant="ghost" className="sr-cta">Save Address<ArrowRight/></Button></form></ShoppingShell>;
}

export const payments=[{name:"Cash on Delivery",image:"cod-art",desc:"Pay when you receive your order at your doorstep."},{name:"bKash",image:"bkash-art",desc:"Pay securely with bKash."},{name:"Nagad",image:"nagad-art",desc:"Pay securely with Nagad."},{name:"Credit / Debit Card",image:"",desc:"Visa, Mastercard, AMEX"}];
export function PaymentReference(){
  const {payment,setPayment}=useCart();
  return <ShoppingShell crumb="Checkout › Payment Method" title="Payment Method" className="co-screen co-payment"><p className="co-subtitle">Choose your preferred payment method.</p><CheckoutSteps step={3}/><div className="co-payments">{payments.map((m,i)=><label key={m.name} className={payment===m.name?"selected":""}><input type="radio" name="payment" checked={payment===m.name} onChange={()=>setPayment(m.name)}/>{m.image?<img src={shoppingImage(m.image)} alt=""/>:<CreditCard/>}<div><h3>{m.name}</h3><p>{m.desc}</p></div>{i===0?<span>Recommended</span>:<ChevronRight/>}</label>)}</div><div className="co-cod-info"><img src={shoppingImage("parcel-art")} alt="Parcel"/><div><h3>{payment==="Cash on Delivery"?"Cash on Delivery Information":`${payment} Information`}</h3>{(payment==="Cash on Delivery"?["Pay with cash when you receive your order","No extra charges","Available across Bangladesh"]:["Pay securely at the next step","No extra charges","Instant payment confirmation"]).map(t=><p key={t}><Check/>{t}</p>)}</div></div><div className="co-secure"><ShieldCheck/><div><h3>100% Secure Payment</h3><p>Your payment information is always safe<br/>and secure with us.</p></div></div><ShoppingCTA to="/checkout/review">Continue to Review</ShoppingCTA></ShoppingShell>;
}

export function ReviewReference(){
  const {lines,address,payment,placeOrder}=useCart();const navigate=useNavigate();const [agree,setAgree]=useState(true);
  const a=addresses.find(x=>x.name===address)??addresses[0]!;const m=payments.find(x=>x.name===payment)??payments[0]!;
  const place=()=>{if(!agree){toast.error("Please accept the Terms & Conditions");return;}placeOrder();navigate({to:"/order-confirmed"});};
  return <ShoppingShell crumb="Checkout › Order Review & Confirm" title="Order Review & Confirm" className="co-screen co-review"><p className="co-subtitle">Please review your order details before placing it.</p><CheckoutSteps step={4}/>{lines.length===0?<EmptyNotice/>:<><Panel title="Delivery Address" icon={<MapPin/>} action={<EditLink to="/checkout/address"/>}><div className="co-review-address"><img src={shoppingImage(a.image)} alt={a.name}/><div><h3>{a.name} {a.name==="Home"&&<span>Default</span>}</h3><p>{a.line1}<br/>{a.line2}<br/>+880 1712 345678</p></div></div></Panel><Panel title={`Order Items (${lines.length})`} icon={<ShoppingCart/>} action={<EditLink to="/checkout" label="Edit Cart"/>}><ItemRows lines={lines} review/></Panel><Panel title="Payment Method" icon={<CreditCard/>} action={<EditLink to="/checkout/payment"/>}><div className="co-review-payment">{m.image?<img src={shoppingImage(m.image)} alt=""/>:<CreditCard/>}<div><h3>{m.name}</h3><p>{m.desc}</p></div><ChevronRight/></div></Panel><Summary lines={lines}/><label className="co-terms"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/>I agree to the <Link to="/support">Terms & Conditions</Link> and <Link to="/support">Privacy Policy</Link></label><Button type="button" variant="ghost" className="sr-cta" onClick={place}><LockKeyhole/>Place Order<ArrowRight/></Button></>}</ShoppingShell>;
}
