import { Link } from "@tanstack/react-router";
import { ArrowRight, ChevronRight, Heart, House, LayoutGrid, List, Menu, Search, ShoppingCart } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DemoControl, ShopBottomNav } from "@/components/shop-navigation";
import logo from "@/assets/logo.png.asset.json";
import { shoppingImage, type ShoppingProduct } from "@/lib/shopping-demo";
import type { ReactNode } from "react";

export function ShoppingShell({children,crumb,title,empty=false,className=""}:{children:ReactNode;crumb:string;title?:string;empty?:boolean;className?:string}) {
 return <div className="mobile-frame"><main className={`baby-screen shopping-reference ${className}`}><header className="sr-header"><DemoControl label="Menu"><Menu/></DemoControl><img src={logo.url} alt="Baby Choice — Everything for Your Little One"/><div><Button asChild variant="ghost" className="sr-circle"><Link to="/search" aria-label="Search"><Search/></Link></Button><Button asChild variant="ghost" className="sr-circle"><Link to="/cart" aria-label="Shopping Cart"><ShoppingCart/><span>{empty?0:3}</span></Link></Button></div></header><nav className="sr-crumb" aria-label="Breadcrumb"><Link to="/" aria-label="Home"><House/></Link><ChevronRight/>{crumb.startsWith("Checkout")?<Link to="/checkout">Checkout</Link>:<span>{crumb}</span>}{crumb.includes(" › ")&&<><ChevronRight/><span>{crumb.split(" › ")[1]}</span></>}</nav>{title&&<h1>{title}</h1>}{children}<ShopBottomNav active="none"/></main></div>;
}
export function ShoppingCTA({to,children}:{to:"/trending"|"/trending/popular"|"/checkout"|"/checkout/address"|"/checkout/address/new"|"/checkout/payment"|"/checkout/review";children:ReactNode}) {return <Button asChild className="sr-cta" variant="ghost"><Link to={to}>{children}<ArrowRight/></Link></Button>;}
export function ShoppingCard({product,compact=false}:{product:ShoppingProduct;compact?:boolean}) {return <article className={`sr-product ${compact?"compact":""}`}><div className="sr-product-art">{product.id==="shampoo"?<Link to="/product/johnsons-baby-shampoo" aria-label="Johnson’s Baby Shampoo"><img src={shoppingImage(`next-${product.id}`)} alt={product.name}/></Link>:<img src={shoppingImage(`next-${product.id}`)} alt={product.name}/>}<span className={`sr-badge ${product.badge==="Best Seller"?"best":product.badge==="New Arrival"?"new":product.badge==="Popular"?"popular":""}`}>{product.badge}</span><DemoControl label={`Wishlist ${product.name}`} className="sr-heart"><Heart/></DemoControl></div><div className="sr-product-copy"><h2>{product.name}</h2><p>{product.description}</p><div className="sr-rating"><span>★★★★★</span> {product.rating}</div><div className="sr-price"><strong>৳ {product.price}</strong>{!compact&&<del>৳ {product.old}</del>}</div><div className="sr-sizes">{product.sizes.map(s=><span key={s}>{s}</span>)}</div><DemoControl label={`Add ${product.name} to Cart`} className="sr-add"><ShoppingCart/>Add to Cart</DemoControl></div></article>;}
export function ViewToggle({popular=false}:{popular?:boolean}) {return <div className="sr-view"><Button asChild variant="ghost" className={!popular?"selected":""}><Link to="/trending" aria-label="Nine-product view"><LayoutGrid/></Link></Button><Button asChild variant="ghost" className={popular?"selected":""}><Link to="/trending/popular" aria-label="Six-product view"><List/></Link></Button></div>;}
