import { Flame, Crown, SlidersHorizontal, ChevronDown, Milk, Heart, Shirt, Baby, BriefcaseBusiness, UserRound, LayoutGrid } from "lucide-react";
import { DemoControl } from "@/components/shop-navigation";
import { ShoppingShell, ShoppingCard, ViewToggle, ShoppingCTA } from "@/components/shopping-reference";
import { shoppingImage, shoppingProducts } from "@/lib/shopping-demo";
export function TrendingReference({popular=false}:{popular?:boolean}) {
 const items=popular?[shoppingProducts[1],shoppingProducts[0],shoppingProducts[2],{...shoppingProducts[3],name:"Cetaphil Baby Daily Lotion",sizes:["400ml"],badge:"Top Rated"},shoppingProducts[4],shoppingProducts[9]]:shoppingProducts.slice(0,9);
 const cats=popular?["All","Feeding","Bath & Skin","Diapers","Wipes","Baby Care"]:["All","Diapers","Feeding","Bath & Skin","Health","Toys","Clothing","Baby Care","Moms"];
 const icons=[LayoutGrid,Baby,Milk,BriefcaseBusiness,Heart,Baby,Shirt,BriefcaseBusiness,UserRound];
 return <ShoppingShell crumb="Trending Products" className={popular?"trending-popular":"trending-main"}>{!popular&&<div className="sr-trending-title"><div><h1>Trending Products</h1><p>Most loved baby products right now</p></div><aside><Crown/><span><b>Popular Today</b><small>Trending among parents</small></span></aside></div>}{popular&&<div className="sr-banner"><img src={shoppingImage("popular-banner")} alt="Trending Products. Most loved baby care products by parents like you."/><ShoppingCTA to="/trending">Shop Trending</ShoppingCTA></div>}<div className="sr-tabs">{cats.map((c,i)=>{const Icon=icons[i]??Baby;return <DemoControl key={c} label={c} className={i===0?"selected":""}><Icon/>{c}</DemoControl>;})}</div><div className="sr-toolbar">{popular&&<DemoControl label="Filter"><SlidersHorizontal/>Filter</DemoControl>}<b>Sort by</b><DemoControl label="Sort products">{popular?"Most Popular":"Trending"}<ChevronDown/></DemoControl><ViewToggle popular={popular}/></div>{!popular&&<div className="sr-banner"><img src={shoppingImage("trend-banner")} alt="Trending Now. Most popular baby products chosen by parents like you. Loved by 10K+ Parents."/><ShoppingCTA to="/trending/popular">Shop Trending Products</ShoppingCTA></div>}<div className={`sr-products ${popular?"two":""}`}>{items.map(p=>p&&<ShoppingCard key={p.id} product={p}/>)}</div></ShoppingShell>;
}
