/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesBabyClothingRouteImport } from './routes/categories.baby-clothing'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CheckoutAddressRouteImport } from './routes/checkout.address'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as CheckoutReviewRouteImport } from './routes/checkout.review'
import { Route as ProductJohnsonsBabyShampooRouteImport } from './routes/product.johnsons-baby-shampoo'
import { Route as TrendingIndexRouteImport } from './routes/trending.index'
import { Route as TrendingPopularRouteImport } from './routes/trending.popular'
import { Route as BrandsJohnsonsIndexRouteImport } from './routes/brands.johnsons.index'
import { Route as BrandsJohnsonsProductsRouteImport } from './routes/brands.johnsons.products'
import { Route as BrandsJohnsonsStoryRouteImport } from './routes/brands.johnsons.story'
import { Route as CheckoutAddressIndexRouteImport } from './routes/checkout.address.index'
import { Route as CheckoutAddressNewRouteImport } from './routes/checkout.address.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesBabyClothingRoute = CategoriesBabyClothingRouteImport.update({
  id: '/categories/baby-clothing',
  path: '/categories/baby-clothing',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutAddressRoute = CheckoutAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutReviewRoute = CheckoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CheckoutRoute,
} as any)
const ProductJohnsonsBabyShampooRoute =
  ProductJohnsonsBabyShampooRouteImport.update({
    id: '/product/johnsons-baby-shampoo',
    path: '/product/johnsons-baby-shampoo',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrendingIndexRoute = TrendingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrendingRoute,
} as any)
const TrendingPopularRoute = TrendingPopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => TrendingRoute,
} as any)
const BrandsJohnsonsIndexRoute = BrandsJohnsonsIndexRouteImport.update({
  id: '/brands/johnsons/',
  path: '/brands/johnsons/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsJohnsonsProductsRoute = BrandsJohnsonsProductsRouteImport.update({
  id: '/brands/johnsons/products',
  path: '/brands/johnsons/products',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsJohnsonsStoryRoute = BrandsJohnsonsStoryRouteImport.update({
  id: '/brands/johnsons/story',
  path: '/brands/johnsons/story',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutAddressIndexRoute = CheckoutAddressIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutAddressRoute,
} as any)
const CheckoutAddressNewRoute = CheckoutAddressNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CheckoutAddressRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/trending': typeof TrendingRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/categories/baby-clothing': typeof CategoriesBabyClothingRoute
  '/checkout/address': typeof CheckoutAddressRouteWithChildren
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/product/johnsons-baby-shampoo': typeof ProductJohnsonsBabyShampooRoute
  '/trending/popular': typeof TrendingPopularRoute
  '/brands/': typeof BrandsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/trending/': typeof TrendingIndexRoute
  '/brands/johnsons/products': typeof BrandsJohnsonsProductsRoute
  '/brands/johnsons/story': typeof BrandsJohnsonsStoryRoute
  '/checkout/address/new': typeof CheckoutAddressNewRoute
  '/brands/johnsons/': typeof BrandsJohnsonsIndexRoute
  '/checkout/address/': typeof CheckoutAddressIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/categories/baby-clothing': typeof CategoriesBabyClothingRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/product/johnsons-baby-shampoo': typeof ProductJohnsonsBabyShampooRoute
  '/trending/popular': typeof TrendingPopularRoute
  '/brands': typeof BrandsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/trending': typeof TrendingIndexRoute
  '/brands/johnsons/products': typeof BrandsJohnsonsProductsRoute
  '/brands/johnsons/story': typeof BrandsJohnsonsStoryRoute
  '/checkout/address/new': typeof CheckoutAddressNewRoute
  '/brands/johnsons': typeof BrandsJohnsonsIndexRoute
  '/checkout/address': typeof CheckoutAddressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/trending': typeof TrendingRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/categories/baby-clothing': typeof CategoriesBabyClothingRoute
  '/checkout/address': typeof CheckoutAddressRouteWithChildren
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/product/johnsons-baby-shampoo': typeof ProductJohnsonsBabyShampooRoute
  '/trending/popular': typeof TrendingPopularRoute
  '/brands/': typeof BrandsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/trending/': typeof TrendingIndexRoute
  '/brands/johnsons/products': typeof BrandsJohnsonsProductsRoute
  '/brands/johnsons/story': typeof BrandsJohnsonsStoryRoute
  '/checkout/address/new': typeof CheckoutAddressNewRoute
  '/brands/johnsons/': typeof BrandsJohnsonsIndexRoute
  '/checkout/address/': typeof CheckoutAddressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/offers'
    | '/order-confirmed'
    | '/search'
    | '/support'
    | '/trending'
    | '/wishlist'
    | '/categories/baby-clothing'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/product/johnsons-baby-shampoo'
    | '/trending/popular'
    | '/brands/'
    | '/categories/'
    | '/checkout/'
    | '/trending/'
    | '/brands/johnsons/products'
    | '/brands/johnsons/story'
    | '/checkout/address/new'
    | '/brands/johnsons/'
    | '/checkout/address/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/login'
    | '/offers'
    | '/order-confirmed'
    | '/search'
    | '/support'
    | '/wishlist'
    | '/categories/baby-clothing'
    | '/checkout/payment'
    | '/checkout/review'
    | '/product/johnsons-baby-shampoo'
    | '/trending/popular'
    | '/brands'
    | '/categories'
    | '/checkout'
    | '/trending'
    | '/brands/johnsons/products'
    | '/brands/johnsons/story'
    | '/checkout/address/new'
    | '/brands/johnsons'
    | '/checkout/address'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/offers'
    | '/order-confirmed'
    | '/search'
    | '/support'
    | '/trending'
    | '/wishlist'
    | '/categories/baby-clothing'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/product/johnsons-baby-shampoo'
    | '/trending/popular'
    | '/brands/'
    | '/categories/'
    | '/checkout/'
    | '/trending/'
    | '/brands/johnsons/products'
    | '/brands/johnsons/story'
    | '/checkout/address/new'
    | '/brands/johnsons/'
    | '/checkout/address/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  SearchRoute: typeof SearchRoute
  SupportRoute: typeof SupportRoute
  TrendingRoute: typeof TrendingRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  CategoriesBabyClothingRoute: typeof CategoriesBabyClothingRoute
  ProductJohnsonsBabyShampooRoute: typeof ProductJohnsonsBabyShampooRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  BrandsJohnsonsProductsRoute: typeof BrandsJohnsonsProductsRoute
  BrandsJohnsonsStoryRoute: typeof BrandsJohnsonsStoryRoute
  BrandsJohnsonsIndexRoute: typeof BrandsJohnsonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/baby-clothing': {
      id: '/categories/baby-clothing'
      path: '/categories/baby-clothing'
      fullPath: '/categories/baby-clothing'
      preLoaderRoute: typeof CategoriesBabyClothingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/address': {
      id: '/checkout/address'
      path: '/address'
      fullPath: '/checkout/address'
      preLoaderRoute: typeof CheckoutAddressRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/review': {
      id: '/checkout/review'
      path: '/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof CheckoutReviewRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/product/johnsons-baby-shampoo': {
      id: '/product/johnsons-baby-shampoo'
      path: '/product/johnsons-baby-shampoo'
      fullPath: '/product/johnsons-baby-shampoo'
      preLoaderRoute: typeof ProductJohnsonsBabyShampooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending/': {
      id: '/trending/'
      path: '/'
      fullPath: '/trending/'
      preLoaderRoute: typeof TrendingIndexRouteImport
      parentRoute: typeof TrendingRoute
    }
    '/trending/popular': {
      id: '/trending/popular'
      path: '/popular'
      fullPath: '/trending/popular'
      preLoaderRoute: typeof TrendingPopularRouteImport
      parentRoute: typeof TrendingRoute
    }
    '/brands/johnsons/': {
      id: '/brands/johnsons/'
      path: '/brands/johnsons'
      fullPath: '/brands/johnsons/'
      preLoaderRoute: typeof BrandsJohnsonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/johnsons/products': {
      id: '/brands/johnsons/products'
      path: '/brands/johnsons/products'
      fullPath: '/brands/johnsons/products'
      preLoaderRoute: typeof BrandsJohnsonsProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/johnsons/story': {
      id: '/brands/johnsons/story'
      path: '/brands/johnsons/story'
      fullPath: '/brands/johnsons/story'
      preLoaderRoute: typeof BrandsJohnsonsStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/address/': {
      id: '/checkout/address/'
      path: '/'
      fullPath: '/checkout/address/'
      preLoaderRoute: typeof CheckoutAddressIndexRouteImport
      parentRoute: typeof CheckoutAddressRoute
    }
    '/checkout/address/new': {
      id: '/checkout/address/new'
      path: '/new'
      fullPath: '/checkout/address/new'
      preLoaderRoute: typeof CheckoutAddressNewRouteImport
      parentRoute: typeof CheckoutAddressRoute
    }
  }
}

interface CheckoutAddressRouteChildren {
  CheckoutAddressNewRoute: typeof CheckoutAddressNewRoute
  CheckoutAddressIndexRoute: typeof CheckoutAddressIndexRoute
}

const CheckoutAddressRouteChildren: CheckoutAddressRouteChildren = {
  CheckoutAddressNewRoute: CheckoutAddressNewRoute,
  CheckoutAddressIndexRoute: CheckoutAddressIndexRoute,
}

const CheckoutAddressRouteWithChildren = CheckoutAddressRoute._addFileChildren(
  CheckoutAddressRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutAddressRoute: typeof CheckoutAddressRouteWithChildren
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutReviewRoute: typeof CheckoutReviewRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutAddressRoute: CheckoutAddressRouteWithChildren,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutReviewRoute: CheckoutReviewRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface TrendingRouteChildren {
  TrendingPopularRoute: typeof TrendingPopularRoute
  TrendingIndexRoute: typeof TrendingIndexRoute
}

const TrendingRouteChildren: TrendingRouteChildren = {
  TrendingPopularRoute: TrendingPopularRoute,
  TrendingIndexRoute: TrendingIndexRoute,
}

const TrendingRouteWithChildren = TrendingRoute._addFileChildren(
  TrendingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  SearchRoute: SearchRoute,
  SupportRoute: SupportRoute,
  TrendingRoute: TrendingRouteWithChildren,
  WishlistRoute: WishlistRoute,
  CategoriesBabyClothingRoute: CategoriesBabyClothingRoute,
  ProductJohnsonsBabyShampooRoute: ProductJohnsonsBabyShampooRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  BrandsJohnsonsProductsRoute: BrandsJohnsonsProductsRoute,
  BrandsJohnsonsStoryRoute: BrandsJohnsonsStoryRoute,
  BrandsJohnsonsIndexRoute: BrandsJohnsonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
